# Generated by Django 3.2.16 on 2023-12-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
